Models/Entities/Livre.cs
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Security.Policy;
    using BookDou.Models.Annotations;
    using Microsoft.EntityFrameworkCore;

    namespace BookDou.Models;

    /// <summary>
    /// Représente un livre avec des informations telles que l'ID, l'ISBN,
    /// le titre, l'auteur, l'éditeur, les dates de publication et d'autres attributs.
    /// </summary>

    //ajout de ce champ pour la contrainte sur l'unicité de l'isbn
    [Index(nameof(Isbn), IsUnique = true)]
    public partial class Livre
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Le champ ISBN est obligatoire.")]
        [RegularExpression(@"^\d+$", ErrorMessage = "Veuillez saisir uniquement des chiffres.")]
        [StringLength(13, MinimumLength = 10, ErrorMessage = "L'ISBN doit comporter entre 10 et 13 caractères.")]
        // vu que je dois pouvoir editer cette methode n'est pas utile..
        //  c'est plutôt une condition dans le controlleur
        // [VerificationIsbnExiste]   
        public string Isbn { get; set; } = null!;

        [Required(ErrorMessage = "Le champ Titre est obligatoire.")]
        [StringLength(100, MinimumLength = 1, ErrorMessage = "Le champ Titre doit être compris entre 1 et 100 caractères.")]
        public string Titre { get; set; } = null!;

        [Display(Name = "Nom de l'auteur.e")]
        [Required(ErrorMessage = "Le champ Nom de l'auteur.e est obligatoire.")]
        [StringLength(80, MinimumLength = 1, ErrorMessage = "Le champ Auteur.e doit être compris entre 1 et 80 caractères.")]
        public string Auteur { get; set; } = null!;

        [Display(Name = "Prénom de l'auteur.e")]
        [NotMapped]
        public string? AuteurPrenom { get; set; }

        [Display(Name= "Éditeur")]
        [Required(ErrorMessage = "Le champ Éditeur est obligatoire.")]
        [StringLength(50, MinimumLength = 1, ErrorMessage = "Le champ Éditeur doit être compris entre 1 et 50 caractères.")]
        public string Editeur { get; set; } = null!;

        [Display(Name = "Date de Publication")]
        [DataType(DataType.Date)]
        public DateTime? DateDePublication { get; set; }

        [DataType(DataType.MultilineText)]
        public string? Description { get; set; }

        [Display(Name = "Image de Couverture")]
        public string? Image { get; set; }

        public DateTime DateCreation { get; set; }

        public DateTime DateModification { get; set; }

        public DateTime? DateSuppression { get; set; }

        public virtual ICollection<CollectionLivre> CollectionLivres { get; set; } = new List<CollectionLivre>();

        public virtual ICollection<Genre> Genres { get; set; } = new List<Genre>();


    }

Controllers/LivreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookDou.Models;
using Newtonsoft.Json;
using Google.Apis.Books.v1;
using Google.Apis.Services;
using Google.Apis.Books.v1.Data;

namespace BookDou.Controllers
{
    public class LivreController : Controller
    {
        private readonly BookdoubddContext _context;

        public LivreController(BookdoubddContext context)
        {
            _context = context;
        }

        // GET: Livre
        public async Task<IActionResult> Index()
        {
            return _context.Livres != null ?
                        View(await _context.Livres.ToListAsync()) :
                        Problem("Entity set 'BookdoubddContext.Livres'  is null.");
        }

        // GET: Livre/Details/5
        public async Task<IActionResult> DetailsLivre(int? id)
        {
            if (id == null || _context.Livres == null)
            {
                return NotFound();
            }

            var livre = await _context.Livres
                .FirstOrDefaultAsync(m => m.Id == id);
            if (livre == null)
            {
                return NotFound();
            }

            return View(livre);
        }

        /// <summary>
        ///    Affiche la vue Ajouter un livre.
        /// </summary>
        /// <remarks>GET: Livre/AjouterLivre</remarks>
        public IActionResult AjouterLivre()
        {
            return View();
        }

        /// <summary>
        ///    Traite la recherche d'un livre à partir d'un code ISBN. Elle vérifie d'abord si le livre existe dans la base de données,
        ///    sinon elle utilise l'API Google Books pour récupérer les informations nécessaires.
        /// </summary>
        /// <remarks>POST: Livre/AjouterLivre</remarks>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AjouterLivre(Livre livre)
        {

            // 1. Vérifie si le livre existe déjà dans la base de données
            var livreExistant = await _context.Livres.FirstOrDefaultAsync(l => l.Isbn == livre.Isbn);

            if (livreExistant == null)
            {
                // 2. Si le livre n'est pas présent en base de données, utilise l'API Google Books
                // Initialisation du service d'accès à l'API Google Books 
                var service = new BooksService(new BaseClientService.Initializer { ApiKey = "AIzaSyAO19PGqvrPcDqVN8DH2mlo2Dl3gPX725I" });

                // Appel a l'API, récupération des information des livres a partir d'un code ISBN
                var volumes = await service.Volumes.List($"isbn:{livre.Isbn}").ExecuteAsync();

                // Aucun livre trouvé
                if (volumes.TotalItems == 0)
                {
                    ViewBag.Message = "Le livre n'a pas été trouvé.";
                    ViewBag.titreLivre = null;
                }
                else
                {
                    // Livre trouvé via l'API

                    // TODO : Si plusieurs livres sont trouvés, les afficher à l'utilisateur et le laisser sélectionner le plus pertinent
                    var livreGoogle = volumes.Items[0];

                    // Récupération des informations du livre depuis l'API
                    var titreApi = livreGoogle.VolumeInfo.Title;
                    var auteurApi = livreGoogle.VolumeInfo.Authors?.FirstOrDefault();
                    DateTime? datePublicationApi = DateTime.TryParse(livreGoogle.VolumeInfo.PublishedDate, out var datePublication) ? datePublication : null;
                    string editeurApi = livreGoogle.VolumeInfo.Publisher;
                    string descriptionApi = livreGoogle.VolumeInfo.Description;

                    // Vérification que toutes les informations nécessaires sont présentes
                    if (!string.IsNullOrEmpty(titreApi) && !string.IsNullOrEmpty(auteurApi) && datePublicationApi.HasValue)
                    {
                        // Crée une instance d'un livre avec toutes les informations récupérées
                        var livreApi = new Livre
                        {
                            Isbn = livre.Isbn,
                            Titre = titreApi,
                            Auteur = auteurApi,
                            DateDePublication = datePublicationApi,
                            Editeur = editeurApi ?? string.Empty,
                            Description = descriptionApi ?? string.Empty
                        };

                        // Stocke le livre trouvé via l'API dans la base de données
                        _context.Livres.Add(livreApi);

                        await _context.SaveChangesAsync();

                        ViewBag.titreLivre = "Le livre " + livreApi.Titre + " a été trouvé.";
                        ViewBag.idLivre = livreApi.Id;
                        ViewBag.Message = null;
                    }
                    else
                    {
                        // Redirige vers le formulaire pré-rempli si certaines informations sont manquantes
                        return RedirectToAction("AjouterLivreFormulairePrerempli", new
                        {
                            isbn = livre.Isbn,
                            titre = titreApi,
                            auteur = auteurApi,
                            datePublication = datePublicationApi,
                            editeur = editeurApi,
                            description = descriptionApi
                        });
                    }
                }

            }
            // Le livre est déjà présent en base de données
            else
            {
                ViewBag.MessageSucces = "Le livre " + livreExistant.Titre + " a été trouvé.";
                ViewBag.idLivre = livreExistant.Id;
                ViewBag.Message = null;
            }

            // Récupération de l'utilisateur connecté et de ses collections
            Utilisateur utilisateurConnecte = JsonConvert.DeserializeObject<Utilisateur>(HttpContext.Session.GetString("Utilisateur"));
            var collections = _context.Collections
                .Where(c => c.UtilisateurId == utilisateurConnecte.Id && c.DateSuppression == null)
                .ToList();
            ViewBag.Collections = collections;

            return View();
        }




        // POST: Livre/AjouterAMaCollection
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AjouterAMaCollection(int collectionId, int livreId)
        {
            var collection = await _context.Collections.FindAsync(collectionId);
            var livre = await _context.Livres.FindAsync(livreId);

            if (collection != null && livre != null)
            {
                var livreAjouterAMaCollection = new CollectionLivre
                {
                    LivreId = livre.Id,
                    CollectionId = collection.Id,
                    Lu = false,
                    DateCreation = DateTime.Now,
                    DateModification = DateTime.Now,
                    Collection = collection,
                    Livre = livre
                };

                var livreDejaDansLaCollection = _context.CollectionLivres.FirstOrDefault(cl => cl.CollectionId == livreAjouterAMaCollection.CollectionId
                                                                                         && cl.LivreId == livreAjouterAMaCollection.LivreId);

                if (livreDejaDansLaCollection == null)
                {
                    _context.CollectionLivres.Add(livreAjouterAMaCollection);
                    await _context.SaveChangesAsync();

                    ViewBag.MessageSucces = "Le livre a été ajouté à la collection avec succès.";
                }
                else
                {
                    ViewBag.Message = "Le livre est déjà présent dans la collection.";
                }


            }
            else
            {
                ViewBag.Message = "La collection ou le livre spécifié n'a pas été trouvé.";
            }

            Utilisateur utilisateurConnecte = JsonConvert.DeserializeObject<Utilisateur>(HttpContext.Session.GetString("Utilisateur"));
            var collections = _context.Collections
                .Where(c => c.UtilisateurId == utilisateurConnecte.Id)
                .ToList();
            ViewBag.Collections = collections;

            return View("AjouterLivre");
        }


        public IActionResult AjouterLivreFormulairePrerempli(string isbn, string titre, string auteur, DateTime? datePublication, string editeur, string description)
        {
            var livre = new Livre
            {
                Isbn = isbn,
                Titre = titre,
                Auteur = auteur,
                DateDePublication = datePublication,
                Editeur = editeur,
                Description = description
            };

            return View(livre);
        }

        // GET: Livre/AjouterLivreFormulaire
        public IActionResult AjouterLivreFormulaire()
        {


            return View();
        }

        // POST: Livre/AjouterLivre
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AjouterLivreFormulaire([Bind("Id,Isbn,Titre,Auteur,AuteurPrenom,Editeur,DateDePublication,Description,Image,DateCreation,DateModification,DateSuppression")] Livre livre)
        {

            if (ModelState.IsValid)
            {

                if (!string.IsNullOrEmpty(livre.AuteurPrenom))
                {
                    livre.Auteur = livre.AuteurPrenom + " " + livre.Auteur;

Views/Livre/AjouterLivre.cshtml
@model BookDou.Models.Livre

@{
    ViewData["Title"] = "Ajouter un Livre";
}

<h1>Ajouter un Livre</h1>

<hr />

<div class="row justify-content-center">
    <div class="col-md-6">
        <h5>Chercher via l'ISBN du livre</h5>
        <form asp-action="AjouterLivre">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Isbn" class="control-label"></label>
                <input asp-for="Isbn" class="form-control" />
                <span asp-validation-for="Isbn" class="text-danger"></span>
            </div>

            <div class="form-group text-center mt-4">
                <input type="submit" value="Chercher le Livre" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">Annuler</a>
            </div>
            <br />
        </form>

        @if (!string.IsNullOrEmpty(ViewBag.Message))
        {
            <div class="alert alert-danger">@ViewBag.Message</div>
        }
        @if (!string.IsNullOrEmpty(ViewBag.MessageSucces))
        {
            <div class="alert alert-success">@ViewBag.MessageSucces</div>

            <div class="text-center mt-3">
                <form asp-action="AjouterAMaCollection" method="post">
                    <label for="collectionId">Choisir une collection :</label>
                    <select name="collectionId" id="collectionId" class="form-control">
                        @foreach (var collection in ViewBag.Collections)
                        {
                            <option value="@collection.Id">@collection.Nom</option>
                        }
                    </select>
                    <input type="hidden" name="livreId" value="@ViewBag.idLivre" />
                    <br />
                    <button type="submit" class="btn btn-secondary btn-sm">Ajouter le livre à ma collection</button>
                </form>
            </div>
        }
    </div>
</div>

<hr />

<div class="row justify-content-center">
    <div class="col-md-6">
        <h5>Ajouter le livre manuellement</h5>
        <div class="text-center mt-3">
            <a asp-controller="Livre" asp-action="AjouterLivreFormulaire" class="btn btn-secondary" role="button" aria-pressed="true">Ajouter le livre manuellement</a>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Livre/AjouterLivreFormulaire.cshtml
@model BookDou.Models.Livre

@{
    ViewData["Title"] = "Ajouter un Livre";
}

<h1>Ajouter un Livre</h1>

<hr />

<div class="row">
    <div class="row justify-content-center">
        <div class="col-md-4">
            <form asp-action="AjouterLivreFormulaire">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Isbn" class="control-label"></label>
                    <input asp-for="Isbn" class="form-control" />
                    <span asp-validation-for="Isbn" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Titre" class="control-label"></label>
                    <input asp-for="Titre" class="form-control" />
                    <span asp-validation-for="Titre" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Auteur" class="control-label"></label>
                    <input asp-for="Auteur" class="form-control" />
                    <span asp-validation-for="Auteur" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="AuteurPrenom" class="control-label"></label>
                    <input asp-for="AuteurPrenom" class="form-control" />
                    <span asp-validation-for="AuteurPrenom" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Editeur" class="control-label"></label>
                    <input asp-for="Editeur" class="form-control" />
                    <span asp-validation-for="Editeur" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DateDePublication" class="control-label"></label>
                    <input asp-for="DateDePublication" class="form-control" />
                    <span asp-validation-for="DateDePublication" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <textarea asp-for="Description" class="form-control"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Image" class="control-label"></label>
                    <input asp-for="Image" class="form-control" />
                    <span asp-validation-for="Image" class="text-danger"></span>
                </div>
                <div class="form-group d-flex justify-content-center my-4">
                    <input type="submit" value="Ajouter le Livre" class="btn btn-primary mx-2" />
                    <a asp-action="Index" class="btn btn-secondary mx-2">Annuler</a>
                </div>

            </form>
        </div>
    </div>
</div>




@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Livre/AjouterLivreFormulairePrerempli.cshtml
@model BookDou.Models.Livre

@{
    ViewData["Title"] = "Ajouter un Livre";
}

<h1>Ajouter un Livre - Compléter les informations</h1>

<hr />

<div class="row">
    <div class="row justify-content-center">
        <div class="col-md-4">
            <form asp-action="AjouterLivreFormulaire" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Isbn" class="control-label"></label>
                    <input asp-for="Isbn" class="form-control" />
                    <span asp-validation-for="Isbn" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Titre" class="control-label"></label>
                    <input asp-for="Titre" class="form-control" />
                    <span asp-validation-for="Titre" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Auteur" class="control-label"></label>
                    <input asp-for="Auteur" class="form-control" />
                    <span asp-validation-for="Auteur" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="AuteurPrenom" class="control-label"></label>
                    <input asp-for="AuteurPrenom" class="form-control" />
                    <span asp-validation-for="AuteurPrenom" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Editeur" class="control-label"></label>
                    <input asp-for="Editeur" class="form-control" />
                    <span asp-validation-for="Editeur" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DateDePublication" class="control-label"></label>
                    <input asp-for="DateDePublication" class="form-control" />
                    <span asp-validation-for="DateDePublication" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <textarea asp-for="Description" class="form-control"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Image" class="control-label"></label>
                    <input asp-for="Image" class="form-control" />
                    <span asp-validation-for="Image" class="text-danger"></span>
                </div>

                <button type="submit" class="btn btn-primary">Soumettre</button>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Livre/Delete.cshtml
@model BookDou.Models.Livre

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Livre</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Isbn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Isbn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Auteur)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Auteur)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Editeur)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Editeur)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateDePublication)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateDePublication)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateCreation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateModification)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateModification)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateSuppression)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateSuppression)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Livre/DetailsLivre.cshtml
@model BookDou.Models.Livre

@{
    ViewData["Title"] = Model.Titre;
}

<div class="container">
    <h1 class="mt-4">@Html.DisplayFor(model => model.Titre)</h1>

    <div class="card mt-4">
        <div class="card-body">
            <h4 class="card-title">Détail</h4>
            <hr />
            <dl class="row">

                <dt class="col-sm-3">
                    Titre
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.Titre)
                </dd>
                <dt class="col-sm-3">
                    Auteur
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.Auteur)
                </dd>
                <dt class="col-sm-3">
                    Éditeur
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.Editeur)
                </dd>
                <dt class="col-sm-3">
                    ISBN
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.Isbn)
                </dd>
                <dt class="col-sm-3">
                    Date de publication
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.DateDePublication)
                </dd>
                <dt class="col-sm-3">
                    Description
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.Description)
                </dd>
            </dl>
        </div>
    </div>

    <div class="mt-4">
        <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model?.Id">Modifier</a>
        <a class="btn btn-secondary" asp-action="Index">Retour à la liste</a>
    </div>
</div>

Views/Livre/EditerLivre.cshtml
@model BookDou.Models.Livre

@{
    ViewData["Title"] = "Editer le livre";
}

<h1>Editer</h1>

<h4>@Model.Titre</h4>

<hr />
<div class="row justify-content-center">
    <div class="col-md-4">
        <form asp-action="EditerLivre">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Isbn" class="control-label"></label>
                <input asp-for="Isbn" class="form-control" />
                <span asp-validation-for="Isbn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Titre" class="control-label"></label>
                <input asp-for="Titre" class="form-control" />
                <span asp-validation-for="Titre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Auteur" class="control-label"></label>
                <input asp-for="Auteur" class="form-control" />
                <span asp-validation-for="Auteur" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Editeur" class="control-label"></label>
                <input asp-for="Editeur" class="form-control" />
                <span asp-validation-for="Editeur" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateDePublication" class="control-label"></label>
                <input asp-for="DateDePublication" class="form-control" />
                <span asp-validation-for="DateDePublication" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group d-flex justify-content-center my-4">
                <input type="submit" value="Sauvegarder" class="btn btn-primary mx-2" />
                <a asp-action="Index" class="btn btn-secondary mx-2">Annuler</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Livre/Index.cshtml
@model IEnumerable<BookDou.Models.Livre>

@{
    ViewData["Title"] = "Livres";
}

<h1>Livres</h1>

<p>
    <a asp-action="AjouterLivre">Ajouter un livre</a>
</p>

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-3">
            <div class="card mb-4">
                <div class="card-body d-flex flex-column align-items-center">
                    <h5 class="card-title text-center mb-3">
                        <a href="@Url.Action("DetailsLivre", new { id = item.Id })">@Html.DisplayFor(modelItem => item.Titre)</a>
                    </h5>
                    <h6 class="card-subtitle mb-2 text-muted">@Html.DisplayFor(modelItem => item.Auteur)</h6>
                    <p class="card-text text-center mb-2">Édition: @Html.DisplayFor(modelItem => item.Editeur)</p>
                    <a href="@Url.Action("EditerLivre", new { id = item.Id })" class="card-link">Modifier</a>
                    <a href="@Url.Action("DetailsLivre", new { id = item.Id })" class="card-link">Details</a>
                    <a href="@Url.Action("Delete", new { id = item.Id })" class="card-link">Delete</a>
                </div>
            </div>
        </div>
    }
</div>